name: Telegram Notify All Pushes

on: 
  push:  # Ñ€ĞµĞ°Ğ³Ğ¸Ñ€ÑƒĞµÑ‚ Ğ½Ğ° Ğ»ÑĞ±Ğ¾Ğ¹ push
    branches:
      - '**'  # Ğ»ÑĞ±Ñ‹Ğµ Ğ²ĞµÑ‚ĞºĞ¸

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ğŸ“Œ ĞĞ¾Ğ²Ñ‹Ğ¹ PUSH:
            ğŸ‘¤ ĞĞ²Ñ‚Ğ¾Ñ€: ${{ github.actor }}
            ğŸ“‚ Ğ ĞµĞ¿Ğ¾Ğ·Ğ¸Ñ‚Ğ¾Ñ€Ğ¸Ğ¹: ${{ github.repository }}
            ğŸŒ¿ Ğ’ĞµÑ‚ĞºĞ°: ${{ github.ref_name }}
            ğŸ’¬ ĞšĞ¾Ğ¼Ğ¼ĞµĞ½Ñ‚Ğ°Ñ€Ğ¸Ğ¹: ${{ github.event.head_commit.message }}
            ğŸ”— Commit: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
